name: ci-workflow-common

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
          fetch-depth: 0
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Install Deps
        run: make init
      - name: Run Tests & Generate Coverage
        run: make test
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./bin/code-coverage-report-codecov.out
          name: codecov-common
          fail_ci_if_error: true
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          fail_ci_if_error: true